# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie-watcher
    username: root
    password: 123456
  application:
    name: Movie-watcher

# 服务器端口
server:
  port: 8080

# mybatis mapper 文件夹位置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    #下划线转驼峰
    map-underscore-to-camel-case: true
